package com.example.helloworld.domain;

/**
 * Immutable summary of salary statistics for one department.
 *
 * <p>Implemented as a <b>Record</b> — all fields are final, and
 * {@code equals()}, {@code hashCode()}, and {@code toString()} are
 * auto-generated by the compiler.
 *
 * <p>Produced by
 * {@link com.example.helloworld.service.SalaryAnalyticsService#salaryByDepartment()}.
 *
 * @param departmentId  the department identifier
 * @param headCount     number of employees in this department
 * @param totalSalary   sum of all salaries in this department
 * @param averageSalary mean salary in this department
 * @param minSalary     lowest individual salary in this department
 * @param maxSalary     highest individual salary in this department
 */
public record DepartmentSalaryReport(
        int    departmentId,
        long   headCount,
        double totalSalary,
        double averageSalary,
        double minSalary,
        double maxSalary
) {
    /** Compact canonical constructor — validates invariants. */
    public DepartmentSalaryReport {
        if (departmentId <= 0)  throw new IllegalArgumentException("departmentId must be positive");
        if (headCount    <  0)  throw new IllegalArgumentException("headCount must not be negative");
        if (totalSalary  <  0)  throw new IllegalArgumentException("totalSalary must not be negative");
        if (averageSalary < 0)  throw new IllegalArgumentException("averageSalary must not be negative");
        if (minSalary    <  0)  throw new IllegalArgumentException("minSalary must not be negative");
        if (maxSalary    <  0)  throw new IllegalArgumentException("maxSalary must not be negative");
        if (minSalary > maxSalary)
            throw new IllegalArgumentException("minSalary must not exceed maxSalary");
    }
}

