package com.example.helloworld.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Immutable DTO representing a single payroll processing record.
 * Implemented as a Java Record — equals(), hashCode(), and toString()
 * are automatically generated by the compiler.
 *
 * payrollMonth      : the month/year for which payroll was processed (e.g. 2026-03-01)
 * processedTimestamp: exact date-time when payroll was run
 */
public record PayrollRecord(
        int id,
        int employeeId,
        double grossSalary,
        double taxAmount,
        double netSalary,
        LocalDate payrollMonth,
        LocalDateTime processedTimestamp
) {
    // Compact canonical constructor for validation
    public PayrollRecord {
        Objects.requireNonNull(payrollMonth,       "payrollMonth must not be null");
        Objects.requireNonNull(processedTimestamp, "processedTimestamp must not be null");
        if (id <= 0)          throw new IllegalArgumentException("id must be positive");
        if (employeeId <= 0)  throw new IllegalArgumentException("employeeId must be positive");
        if (grossSalary < 0)  throw new IllegalArgumentException("grossSalary must not be negative");
        if (taxAmount < 0)    throw new IllegalArgumentException("taxAmount must not be negative");
        if (taxAmount > grossSalary)
            throw new IllegalArgumentException("taxAmount cannot exceed grossSalary");

        // Ensure netSalary is consistent
        double expectedNet = grossSalary - taxAmount;
        if (Math.abs(netSalary - expectedNet) > 0.001)
            throw new IllegalArgumentException(
                    String.format("netSalary (%.2f) must equal grossSalary - taxAmount (%.2f)",
                            netSalary, expectedNet));
    }

    /**
     * Factory method — calculates netSalary automatically.
     */
    public static PayrollRecord of(int id,
                                   int employeeId,
                                   double grossSalary,
                                   double taxAmount,
                                   LocalDate payrollMonth,
                                   LocalDateTime processedTimestamp) {
        return new PayrollRecord(id, employeeId, grossSalary, taxAmount,
                grossSalary - taxAmount, payrollMonth, processedTimestamp);
    }
}

